# Generated by Django 2.2.6 on 2019-10-18 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capytool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.CharField(default='anhlee2101@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='idi',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
