# Generated by Django 2.2.6 on 2019-10-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capytool', '0002_auto_20191018_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
