# Generated by Django 2.2.6 on 2019-10-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capytool', '0003_auto_20191018_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_ttc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tva',
            field=models.CharField(max_length=200),
        ),
    ]
