# Generated by Django 2.2.6 on 2019-10-23 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capytool', '0005_auto_20191018_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_ttc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tva',
            field=models.IntegerField(default=0),
        ),
    ]
