# Generated by Django 2.2.6 on 2019-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capytool', '0006_auto_20191023_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_ttc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tva',
            field=models.FloatField(default=0),
        ),
    ]
